# Numpy Basic

In [92]:
import numpy as np

## data type

array의 dtype을 본다. 

In [93]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

In [94]:
arr.dtype

dtype('int32')

In [96]:
arr = np.array([[1., 2, 3], [1, 2, 3]])

In [97]:
arr.dtype

dtype('float64')

.astype()으로 datatype을 변환 가능

In [99]:
arr.astype('float32')

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float32)

In [100]:
arr.astype('int32')

array([[1, 2, 3],
       [1, 2, 3]])

In [101]:
arr.astype(np.uint8)

array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

In [102]:
arr = arr.astype('int32')
arr.dtype

dtype('int32')

In [103]:
arr = np.array([[1., 2, 3], [1, 2, 3]], dtype = 'uint8')
arr.dtype

dtype('uint8')

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [104]:
arr.ndim

2

In [106]:
len(arr.shape)

2

size 확인

In [108]:
arr.size

6

dtype 확인

In [109]:
arr.dtype

dtype('uint8')

## Reshape

In [110]:
arr.shape

(2, 3)

In [111]:
arr

array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

Reshape 

In [113]:
arr = arr.reshape([1, 6])

In [114]:
arr.shape

(1, 6)

In [115]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
arr.shape

(2, 3)

In [118]:
arr  = arr.reshape([6])

In [119]:
arr.shape

(6,)

Reshape, -1 활용

In [121]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

In [125]:
arr = arr.reshape(-1) # flatten하는것과 동일
arr

array([1, 2, 3, 1, 2, 3])

In [126]:
arr.shape

(6,)

In [127]:
arr = arr.reshape(1, -1)
arr

array([[1, 2, 3, 1, 2, 3]])

In [128]:
arr = arr.reshape(-1, 3)
arr

array([[1, 2, 3],
       [1, 2, 3]])

random array 생성

In [131]:
arr = np.random.randn(8, 8)
arr

array([[-0.77450797, -1.27029392,  0.04817588,  0.68244554, -1.15906856,
         1.45738473,  0.77097575,  0.61327167],
       [-0.80050109, -0.75390445,  0.10210669,  0.69646604,  0.53988287,
        -0.18945747, -1.45600603,  0.62558298],
       [ 0.25781673,  0.07187523,  0.10460766,  0.21858357,  0.45065767,
         0.51865326, -1.9475968 , -2.33348841],
       [ 0.15766467, -1.07947779,  0.77146865, -0.85002821, -0.27454461,
         1.22850061, -0.01864487,  0.65589387],
       [-0.47180643, -0.05426033, -0.07164842,  0.01997495,  0.22257438,
         0.88980712, -0.85125103,  0.12067313],
       [ 0.63802489,  0.61195114,  0.75655084,  0.24130943, -0.65560951,
        -0.61959913, -0.20410791,  0.07696819],
       [-0.36729064, -0.16681104,  0.5024832 ,  1.13321191, -0.45269656,
         0.73558245,  1.96342963,  1.37885634],
       [-1.98357365, -0.79439024, -0.67496067, -0.47401232,  2.26419213,
         0.44983934, -0.98484448, -1.40130314]])

In [133]:
arr = arr.reshape([32, 2])
arr.shape

(32, 2)

3차원으로 늘리기

In [134]:
arr = arr.reshape(-1, 2, 1)
arr.shape

(32, 2, 1)

In [135]:
arr

array([[[-0.77450797],
        [-1.27029392]],

       [[ 0.04817588],
        [ 0.68244554]],

       [[-1.15906856],
        [ 1.45738473]],

       [[ 0.77097575],
        [ 0.61327167]],

       [[-0.80050109],
        [-0.75390445]],

       [[ 0.10210669],
        [ 0.69646604]],

       [[ 0.53988287],
        [-0.18945747]],

       [[-1.45600603],
        [ 0.62558298]],

       [[ 0.25781673],
        [ 0.07187523]],

       [[ 0.10460766],
        [ 0.21858357]],

       [[ 0.45065767],
        [ 0.51865326]],

       [[-1.9475968 ],
        [-2.33348841]],

       [[ 0.15766467],
        [-1.07947779]],

       [[ 0.77146865],
        [-0.85002821]],

       [[-0.27454461],
        [ 1.22850061]],

       [[-0.01864487],
        [ 0.65589387]],

       [[-0.47180643],
        [-0.05426033]],

       [[-0.07164842],
        [ 0.01997495]],

       [[ 0.22257438],
        [ 0.88980712]],

       [[-0.85125103],
        [ 0.12067313]],

       [[ 0.63802489],
        [ 0.61195

## Ravel

1차원으로 flatten 시키기

In [136]:
arr.shape

(32, 2, 1)

In [141]:
arr = arr.ravel()
arr.shape

(64,)

arr의 차원을 1로 바꿔줌  
나중에 배울 layer를 flatten 할 때 같은 기능이라 생각하면 됨 

arr.reshape(-1) 와 같음

In [142]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [143]:
arr.shape

(64,)

In [144]:
arr = np.expand_dims(arr, 0)
arr.shape

(1, 64)

In [146]:
arr = np.random.randn(8, 8)
arr = arr.ravel()
arr.shape

(64,)

In [147]:
arr = np.expand_dims(arr, -1)
arr.shape

(64, 1)

In [148]:
arr = np.random.randn(8, 8)
arr = arr.ravel()
arr.shape

(64,)

In [149]:
arr = np.expand_dims(np.expand_dims(arr, -1), 0)
arr.shape

(1, 64, 1)

## zeros & ones

#### np.zeros

0으로 채워진 numpy array를 만들 수 있음

In [3]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
zeros = np.zeros(1)
zeros

array([0.])

#### np.ones

In [6]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
ones = np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

#### np.arange

In [13]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [15]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

In [16]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

사용 예제

In [25]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Index

In [18]:
nums = [1, 2, 3, 4, 5]

In [21]:
print(nums[2])
print(nums[2:])

3
[3, 4, 5]


In [26]:
nums = [1, 2, 3, 4, [1, 2, 3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [27]:
nums[4]

[1, 2, 3]

In [30]:
arr[1]

array([3, 4, 5])

In [33]:
arr[1][2]

5

In [32]:
arr[1, 2]

5

# Slicing

In [35]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [36]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

## Boolean Indexing

In [38]:
data = np.random.randn(3, 3)
data

array([[-0.23301404, -0.54509445, -0.44946097],
       [-1.59009457, -1.00633926, -0.35984182],
       [ 0.42405397,  2.05187893, -0.35205801]])

In [40]:
data <= 0

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [44]:
data[data <= 0] = 1
data

array([[1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        ],
       [0.42405397, 2.05187893, 1.        ]])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

tensor의 차원이 같은것이 있다면 그것으로 계산해줌

In [46]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [49]:
arr + np.array([1, 1, 1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [53]:
arr + np.array([1, 2]) # 차원이 다르면 안됨

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

## Math Function

In [54]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [55]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [56]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [57]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [60]:
arr = np.random.randint(2, size=27).reshape(3, 3, 3)
arr_2 = np.random.randint(2, size=9).reshape(3, 3)

In [61]:
arr

array([[[1, 1, 0],
        [1, 1, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 0, 0],
        [0, 1, 0]],

       [[0, 0, 1],
        [1, 1, 0],
        [1, 0, 1]]])

In [62]:
arr.shape

(3, 3, 3)

In [63]:
arr_2

array([[0, 0, 0],
       [1, 1, 1],
       [1, 0, 0]])

In [64]:
arr_2.shape

(3, 3)

In [65]:
arr + arr_2

array([[[1, 1, 0],
        [2, 2, 1],
        [2, 0, 0]],

       [[1, 1, 1],
        [2, 1, 1],
        [1, 1, 0]],

       [[0, 0, 1],
        [2, 2, 1],
        [2, 0, 1]]])

In [67]:
arr * arr_2

array([[[0, 0, 0],
        [1, 1, 0],
        [1, 0, 0]],

       [[0, 0, 0],
        [1, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [1, 1, 0],
        [1, 0, 0]]])

In [68]:
np.sum(arr)

15

In [70]:
np.sum(arr + arr_2)

27

In [72]:
np.max(arr + arr_2)

2

In [73]:
np.min(arr + arr_2)

0

In [76]:
np.max(arr + arr_2, -1)

array([[1, 2, 2],
       [1, 2, 1],
       [1, 2, 2]])

In [79]:
arr + arr_2

array([[[1, 1, 0],
        [2, 2, 1],
        [2, 0, 0]],

       [[1, 1, 1],
        [2, 1, 1],
        [1, 1, 0]],

       [[0, 0, 1],
        [2, 2, 1],
        [2, 0, 1]]])

In [78]:
np.sum(arr + arr_2, 0)

array([[2, 2, 2],
       [6, 5, 3],
       [5, 1, 1]])

In [81]:
np.sum(arr + arr_2, axis = -1)

array([[2, 5, 2],
       [3, 4, 2],
       [1, 5, 3]])

In [82]:
np.mean(arr)

0.5555555555555556

In [86]:
arr = np.array([1, 6, 3, 7, 3, 2, 9, 0, 2])
arr

array([1, 6, 3, 7, 3, 2, 9, 0, 2])

In [87]:
# 6번째 index의 숫가자 가장 크다
np.argmax(arr)

6

In [88]:
np.argmin(arr)

7

In [89]:
arr = np.array([3, 5, 6, 6, 3, 3, 1])
arr

array([3, 5, 6, 6, 3, 3, 1])

In [91]:
# set과 같은 역할
np.unique(arr)

array([1, 3, 5, 6])